feat: adding check for go mod tidy
lietu/go-pre-commit pull request #2
Opened 2021-04-16 21:00 UTC by asishrs

2021-04-17 07:22 UTC, lietu requested changes
Thanks for the PR!

I took a look and ran `pre-commit run --all-files` locally and noticed there were a few things it was complaining about, some small automatic edit to `README.md` and:

```
commands\go-mod-tidy.go:12:17: SA4021: x = append(y) is equivalent to x = y (staticcheck)
                runTool("go", append([]string{"mod", "tidy"}))
```

Could you please fix these? :)

2021-04-17 07:22 UTC, lietu commented on commands/go-mod-tidy.go
> +		runTool("go", append([]string{"mod", "tidy"}))
Running `pre-commit run --all-files` on the repo itself complains about this line:

```
commands\go-mod-tidy.go:12:17: SA4021: x = append(y) is equivalent to x = y (staticcheck)
                runTool("go", append([]string{"mod", "tidy"}))
```

Compared to many of the other commands the main difference is that it does not include `args...`. It does not seem `go mod tidy` currently accepts all that many arguments, but there is *an* argument it accepts, and we could support it and future arguments by including `args...`.

Changing the line to:

```
runTool("go", append([]string{"mod", "tidy"}, args...))
```

Should fix the issue.

2021-04-17 07:28 UTC, lietu commented
Also when I run `go mod tidy` locally with your branch I get a number of changes to `go.sum` - maybe you need to run it again?

2021-04-19 17:35 UTC, asishrs commented on commands/go-mod-tidy.go
> +		runTool("go", append([]string{"mod", "tidy"}))
Sorry for that. fixed it

2021-04-19 19:49 UTC, merged

2021-04-19 19:49 UTC, lietu commented
Thanks for the contribution!